# YOUR NAME OR TITLE OF YOUR SITE
name: Follie Abbigliamento

# YOUR BRAND/PERSONAL TAGLINE
tagline: Abbigliamento donna a Prato, via Pistoiese 615/Q

# YOUR/BRAND IMAGE URL
Image_URL: https://github.com/follieprato/links/blob/master/assets/images/logo.png?raw=true

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://picsum.photos/1080?nocache=

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
    # FACEBOOK
  - Name: Facebook
    URL: https://www.facebook.com
    Username: follieabbigliamentoprato
    Color: '#3b5998'
    Icon-Class: fab fa-facebook

    # INSTAGRAM
  - Name: Instagram
    URL: https://www.instagram.com
    Username: follie_abbigliamento_prato
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram

    # EMAIL
  - Name: Email
    URL: 'mailto:admin@lefollie.shop'
    Icon-Class: fas fa-envelope
    Color: '#e17055'
    Text_Color: '#ffffff'

    # WHATSAPP
  - Name: WhatsApp
    URL: https://chat.whatsapp.com
    Username: 'ClFo5jokUVa3CjvKahFXiX'
    Color: '#25d366'
    Icon-Class: fab fa-whatsapp

    # CUSTOM LINK
  - Name: Site
    URL: https://lefollie.shop
    Icon-Class: fas fa-link
    Color: '#ffb142'
    Text_Color: '#ffffff'


# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: 'No'

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
